### PR TITLE
Add credo static code analyzer to the project

### PR DESCRIPTION
**Pull request by tspenov**
- [x] Add credo static code analyzer to the project
- [x] Add style guide check in CI
- [x] Fixed some style inconsistencies - mostly: grouping module aliasing, space around assignment,
start piping with raw value, increased max line length to `120`c, added `@moduledoc false` to existing modules without documentation

[//]: # (#### Additional deploy notes)

[//]: # (#### Screenshots)

### CODE REVIEW

**Comment by valo** [comment]
I am a bit split on the `Credo.Check.Refactor.PipeChainStart`. I am not convinced that it makes the code more readable in all the cases. For example when something it fetched from the DB with `Repo.get`: https://github.com/valo/melodica-inventory/pull/29/files#diff-b8b62535132924cadaee1581679eeb25R11

May be we should disable it and manage these pipes by hand? @LucoLe, any opinions here?

**Comment by tspenov** [comment]
I am also 50/50 cause for me it's a bit more readable but adds additional lines of code. I am ok with disabling it.

**Comment by LucoLe** [comment]
I don't have strong opinion on this topic I think what @tspenov proposes is a bit more readable in the majority of the occurrences but in some cases can be more obfuscated (https://github.com/valo/melodica-inventory/pull/29/files#diff-fcb397f83d32355349c7e8393f065820R37). The other syntax brings some inconsistencies when you use the pipe operator (sometimes you start a pipe with a single variable and sometimes you can start with a method call). I lean toward what @tspenov proposes a little bit more because I find the code to be a little better structured that way (although I kinda don't like that you bring a new line after the `=` sign) but both are ok.

**Comment by valo** [comment]
I am more inclined to disable that check and manage the pipe layout ourselves.

**Comment by tspenov** [comment]
ok, I'll disable it 👍 . I'll close this PR and make another one because it will be easier with the new changes in master.

**Comment by tspenov** [comment]
closing this one: a lot of conflicts after 1.3 upgrade, also disabling the rule will mean a lot of changes to be rolled back

**Pull request closed without merging**
